version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: nextcloud_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always

  app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud_app
    restart: always
    ports:
      - 8080:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
    depends_on:
      - db
      - redis
      - onlyoffice

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
    ports:
      - 8081:80

  configurator:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud_configurator
    depends_on:
      - app
    entrypoint: ["/bin/bash", "-c", "chmod +x /config/init_config.sh && /config/init_config.sh"]
    volumes:
      - nextcloud_config:/config
      - nextcloud_data:/data
      - ./init_config.sh:/config/init_config.sh:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TRUSTED_DOMAIN_0=${TRUSTED_DOMAIN_0}
      - TRUSTED_DOMAIN_1=${TRUSTED_DOMAIN_1}
      - TRUSTED_DOMAIN_2=${TRUSTED_DOMAIN_2}
      - ONLYOFFICE_JWT_SECRET=${ONLYOFFICE_JWT_SECRET}
      - DEFAULT_PHONE_REGION=${DEFAULT_PHONE_REGION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}

volumes:
  db_data:
  nextcloud_config:
  nextcloud_data:
